export const DATE_SET = 'DATE_SET';

export const VIDEO_POINTS_REQUEST = 'VIDEO_POINTS_REQUEST';
export const VIDEO_POINTS_RESPONSE = 'VIDEO_POINTS_RESPONSE';
export const VIDEO_POINTS_ERROR_RESPONSE = 'VIDEO_POINTS_ERROR_RESPONSE';
